### ISSUE TITLE
Issue/Typo in OAuth How To Guide (Java)

### ISSUE THREAD

**Issue by kevin-king** [IntuitDeveloper/SampleApp-TimeTracking_Invoicing-Java#1]
In the wiki docs, the third parameter of the `setAccessTokenForCompany` method, in the `public interface OAuthInfoProvider` interface, should accept `String` as its parameter type instead of `AccessTokenValues`. This is how it appears in the actual source code.

**Comment by vishal-aggarwal** [comment]
Hi Kevin,
Thank you for the comment, I have updated the wiki documentation.

Thank you,
Vishal
