### ISSUE TITLE
Bug on your website

### ISSUE THREAD

**Issue by GabrielSuttner** [IntuitDeveloper/SampleApp-TimeTracking_Invoicing-Java#4]
I don't know where to report this bug at but I can't do stuff on your website (https://developer.intuit.com/) because it is throwing an error. Since this will send you a notification I am posting this here. 
I'm on https://developer.intuit.com/app/developer/appdetail/list-on-app-store/app-listing-detail?appId=djQuMTo6OGQzYmJlYTI3Yg:047ecf67-603b-4204-88e8-551ac05e4b55&locale=en-US&isReviewMode=true#support-container

And when I input all of the fields, everything is fine until I try to input data into the support section. It seems as if the variable that is assigned to each of the inputs isn't hooked up correctly I get the following error. 

Failure handling text changes Object TypeError: Cannot set property 'supportDescription' of undefined
    at 18.e9776fbb6250515e3992df6283a7.js:2
    at Object.ki (react-dom.min.js:176)
    at ji (react-dom.min.js:13)
    at mi (react-dom.min.js:13)
    at lf (react-dom.min.js:13)
    at wi (react-dom.min.js:187)
    at Array.forEach (<anonymous>)
    at Kd (react-dom.min.js:32)
    at pc (react-dom.min.js:32)
    at Wf (react-dom.min.js:34)

Please get this fixed as soon as possible.

**Comment by williamlorfing** [comment]
Hi Gabriel,

I sent this to development and they are looking at it and they are seeing
the same issue.

Thanks for reporting this.

If you have trouble in the future, you can go to
https://help.developer.intuit.com/s/ and post something on the forums OR
under Help - Developer Resources, there is a Contact Support link there.

Regards,

William Lorfing
Intuit Developer Group, Developer Relations
